### ISSUE TITLE
Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by simsketch** [blivesta/animsition#69]
C:\repos\animsition [master +0 ~1 -0]> gulp build
module.js:338
    throw err;
          ^
Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\repos\animsition\gulpfile.js:1:82)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
C:\repos\animsition [master +0 ~1 -0]>

I tried removing autoprefixer from package.json devdependencies but that didn't help my situation.

**Comment by simsketch** [comment]
Whoops...forgot to npm install.
